# Copyright (c) 2025 SenseTime. All Rights Reserved.
# Author: LazyLLM Team,  https://github.com/LazyAGI/LazyLLM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

firms = {
    "SenseNova": ["llm", "embedding"],
    "Deepseek": ["llm"],
    "Qwen": ["llm", "embedding", "reranker"],
    "GLM": ["llm", "embedding", "reranker"],
    "Doubao": ["llm", "embedding"],
    "Kimi": ["llm"],
    "OpenAI": ["llm", "embedding"],
    "SiliconFlow": ["llm", "embedding", "reranker", "sd", "tts", "stt", "vqa"],
}

# 模型类别
model_kinds = {
    "localLLM": "大模型",
    "OnlineLLM": "大模型",
    "Embedding": "向量模型",
    "reranker": "重排序",
    "VQA": "视觉问答",
    "SD": "文生图",
    "TTS": "文字转语音",
    "STT": "语音转文字",
}
# 模型仓库卡片类别
model_card_kinds = {
    "localLLM": "大模型（localLLM）",
    "OnlineLLM": "大模型（OnlineLLM）",
    "Embedding": "向量模型（Embedding）",
    "reranker": "重排序（Reranker）",
    "VQA": "视觉问答（VQA）",
    "SD": "文生图（SD）",
    "TTS": "文字转语音（TTS）",
    "STT": "语音转文字（STT）",
}

# local_finetune_model_list = [
#     "Baichuan-13B-Chat",
#     "Baichuan-7B",
#     "Baichuan2-13B-Chat",
#     "Baichuan2-7B-Chat",
#     "chatglm3-6b",
#     "glm-4-9b-chat",
#     "internlm2-20b",
#     "internlm2-7b",
#     "internlm2-chat-1_8b",
#     "internlm2-chat-1_8b-sft",
#     "internlm2-chat-20b",
#     "internlm2-chat-20b-sft",
#     "internlm2-chat-7b",
#     "internlm2_5-7b-chat",
#     "Llama-2-13b",
#     "Llama-2-70b",
#     "Llama-2-7b",
#     "Qwen-14B",
#     "Qwen-1_8B",
#     "Qwen-72B",
#     "Qwen-7B",
#     "Qwen1.5-0.5B-Chat",
#     "Qwen1.5-1.8B",
#     "Qwen1.5-14B",
#     "Qwen1.5-14B-Chat",
#     "Qwen1.5-4B",
#     "Qwen1.5-72B",
#     "Qwen1.5-7B"
# ]

online_model_list = {
    "SenseNova": {
        "llm_list": [
            {"model_name": "SenseChat-5", "support_finetune": False, "type": "LLM"},
            {"model_name": "SenseChat", "support_finetune": False, "type": "LLM"},
            {"model_name": "SenseChat-32K", "support_finetune": False, "type": "LLM"},
            {"model_name": "SenseChat-128K", "support_finetune": False, "type": "LLM"},
            {"model_name": "SenseChat-Turbo", "support_finetune": False, "type": "LLM"},
        ],
        "embedding_list": [
            {
                "model_name": "nova-embedding-stable",
                "support_finetune": False,
                "type": "embedding",
            }
        ],
        "vqa_list": [
            {"model_name": "SenseNova-V6-5-Pro", "support_finetune": False, "type": "VQA"},
            {"model_name": "SenseNova-V6-5-Turbo", "support_finetune": False, "type": "VQA"},
            {"model_name": "SenseNova-V6-Turbo", "support_finetune": False, "type": "VQA"},
            {"model_name": "SenseNova-V6-Pro", "support_finetune": False, "type": "VQA"}
        ],
    },
    "Deepseek": {
        "llm_list": [
            {"model_name": "deepseek-chat", "support_finetune": False, "type": "LLM"}
        ]
    },
    "Qwen": {
        "reranker_list": [
            {"model_name": "gte-rerank", "support_finetune": False, "type": "rerank"},
        ],
        "embedding_list": [
            {
                "model_name": "text-embedding-v1",
                "support_finetune": False,
                "type": "embedding",
            },
            {
                "model_name": "text-embedding-v2",
                "support_finetune": False,
                "type": "embedding",
            },
            {
                "model_name": "text-embedding-v3",
                "support_finetune": False,
                "type": "embedding",
            },
        ],
        "llm_list": [
            {"model_name": "qwen-plus", "support_finetune": False, "type": "LLM"},
            {"model_name": "qwen-turbo-0919", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "qwen2.5-0.5b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2.5-1.5b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2.5-3b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2.5-7b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2.5-14b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2.5-32b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2.5-72b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen-turbo-latest",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-plus-0919", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "qwen-plus-latest",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-max-0919", "support_finetune": False, "type": "LLM"},
            {"model_name": "qwen-max-latest", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "qwen2-72b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2-7b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2-0.5b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2-1.5b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen2-57b-a14b-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-long", "support_finetune": False, "type": "LLM"},
            {"model_name": "qwen-max-0428", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "qwen1.5-110b-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-7b-chat", "support_finetune": True, "type": "LLM"},
            {
                "model_name": "qwen-1.8b-longcontext-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-1.8b-chat", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "qwen1.5-0.5b-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-72b-chat", "support_finetune": True, "type": "LLM"},
            {"model_name": "qwen-14b-chat", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "qwen-max-longcontext",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-max-1201", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "qwen1.5-32b-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen1.5-72b-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qqwen1.5-7b-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen1.5-1.8b-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "qwen1.5-14b-chat",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "qwen-max", "support_finetune": False, "type": "LLM"},
            {"model_name": "qwen-turbo", "support_finetune": True, "type": "LLM"},
            {"model_name": "qwen-max-0107", "support_finetune": False, "type": "LLM"},
            {"model_name": "qwen-max-0403", "support_finetune": False, "type": "LLM"},
        ],
        "tts_list": [
            {"model_name": "qwen-tts", "support_finetune": False, "type": "TTS"}
        ],
        "sd_list": [
            {"model_name": "wanx2.1-t2i-turbo", "support_finetune": False, "type": "SD"}
        ],
        "vqa_list": [
            {"model_name": "qwen-vl-plus", "support_finetune": False, "type": "VQA"}
        ],
    },
    "GLM": {
        "embedding_list": [
            {
                "model_name": "embedding-2",
                "support_finetune": False,
                "type": "embedding",
            },
            {
                "model_name": "embedding-3",
                "support_finetune": False,
                "type": "embedding",
            },
        ],
        "llm_list": [
            {"model_name": "glm-4", "support_finetune": False, "type": "LLM"},
            {"model_name": "glm-4-plus", "support_finetune": False, "type": "LLM"},
            {"model_name": "glm-4-0520", "support_finetune": False, "type": "LLM"},
            {"model_name": "glm-4-air", "support_finetune": False, "type": "LLM"},
            {"model_name": "glm-4-long", "support_finetune": False, "type": "LLM"},
            {"model_name": "glm-4-airx", "support_finetune": False, "type": "LLM"},
            {"model_name": "glm-4-flashx", "support_finetune": False, "type": "LLM"},
            {"model_name": "glm-4-flash", "support_finetune": False, "type": "LLM"},
            {"model_name": "chatglm3-6b", "support_finetune": True, "type": "LLM"},
            {"model_name": "chatglm_12b", "support_finetune": True, "type": "LLM"},
            {"model_name": "chatglm_32b", "support_finetune": True, "type": "LLM"},
            {"model_name": "chatglm_66b", "support_finetune": True, "type": "LLM"},
            {"model_name": "chatglm_130b", "support_finetune": True, "type": "LLM"},
        ],
        "reranker_list": [
            {"model_name": "rerank", "support_finetune": True, "type": "rerank"}
        ],
        "stt_list": [
            {"model_name": "glm-asr", "support_finetune": False, "type": "STT"}
        ],
    },
    "Doubao": {
        "llm_list": [
            {
                "model_name": "doubao-1-5-pro-32k-250115",
                "support_finetune": False,
                "type": "LLM",
            }
        ],
        "embedding_list": [
            {
                "model_name": "doubao-embedding-text-240715",
                "support_finetune": False,
                "type": "embedding",
            }
        ],
    },
    "Kimi": {
        "llm_list": [
            {"model_name": "moonshot-v1-8k", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "moonshot-v1-128k",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "moonshot-v1-32kK",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "moonshot-v1-auto",
                "support_finetune": False,
                "type": "LLM",
            },
        ]
    },
    "OpenAI": {
        "embedding_list": [
            {
                "model_name": "text-embedding-ada-002",
                "support_finetune": False,
                "type": "embedding",
            },
            {
                "model_name": "text-embedding-3-large",
                "support_finetune": False,
                "type": "embedding",
            },
            {
                "model_name": "text-embedding-3-small",
                "support_finetune": False,
                "type": "embedding",
            },
        ],
        "llm_list": [
            {"model_name": "gpt-3.5-turbo", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "gpt-3.5-turbo-0125",
                "support_finetune": True,
                "type": "LLM",
            },
            {
                "model_name": "gpt-3.5-turbo-1106",
                "support_finetune": True,
                "type": "LLM",
            },
            {
                "model_name": "gpt-3.5-turbo-instruct",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "gpt-3.5-turbo-instruct-0914",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "gpt-4-1106-preview",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "gpt-4-0125-preview",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "gpt-4-turbo-preview",
                "support_finetune": False,
                "type": "LLM",
            },
            {"model_name": "gpt-4-turbo", "support_finetune": False, "type": "LLM"},
            {
                "model_name": "gpt-4-turbo-2024-04-09",
                "support_finetune": False,
                "type": "LLM",
            },
            {
                "model_name": "gpt-3.5-turbo-0613",
                "support_finetune": True,
                "type": "LLM",
            },
            {"model_name": "babbage-002", "support_finetune": True, "type": "LLM"},
            {"model_name": "davinci-002", "support_finetune": True, "type": "LLM"},
            {"model_name": "gpt-4-0613", "support_finetune": True, "type": "LLM"},
        ],
    },
    "SiliconFlow": {
        "llm_list": [
            {"model_name": "Qwen/QwQ-32B", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen3-32B", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen3-14B", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen3-30B-A3B", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen3-235B-A22B", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen2.5-72B-Instruct", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen2.5-72B-Instruct-128K", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen2.5-32B-Instruct", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen2.5-14B-Instruct", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen2.5-7B-Instruct", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen2.5-Coder-32B-Instruct", "support_finetune": False, "type": "LLM"},
            {"model_name": "Qwen/Qwen2.5-Coder-7B-Instruct", "support_finetune": False, "type": "LLM"},
            {"model_name": "deepseek-ai/DeepSeek-V3", "support_finetune": False, "type": "LLM"},
            {"model_name": "deepseek-ai/DeepSeek-V2.5", "support_finetune": False, "type": "LLM"},
            {"model_name": "deepseek-ai/DeepSeek-R1", "support_finetune": False, "type": "LLM"},
            {"model_name": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", "support_finetune": False, "type": "LLM"},
            {"model_name": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", "support_finetune": False, "type": "LLM"},
            {"model_name": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B", "support_finetune": False, "type": "LLM"},
            {"model_name": "THUDM/GLM-4.1V-9B-Thinking", "support_finetune": False, "type": "LLM"},
            {"model_name": "zai-org/GLM-4.6", "support_finetune": False, "type": "LLM"},
            {"model_name": "zai-org/GLM-4.5", "support_finetune": False, "type": "LLM"},
            {"model_name": "zai-org/GLM-4.5-Air", "support_finetune": False, "type": "LLM"},
            {"model_name": "moonshotai/Kimi-K2-Instruct-0905", "support_finetune": False, "type": "LLM"},
            {"model_name": "moonshotai/Kimi-Dev-72B", "support_finetune": False, "type": "LLM"},
            {"model_name": "MiniMaxAI/MiniMax-M2", "support_finetune": False, "type": "LLM"},
            {"model_name": "MiniMaxAI/MiniMax-M1-80k", "support_finetune": False, "type": "LLM"},
        ],
        "embedding_list": [
            {"model_name": "BAAI/bge-m3", "support_finetune": False, "type": "embedding"},
            {"model_name": "BAAI/bge-large-zh-v1.5", "support_finetune": False, "type": "embedding"},
            {"model_name": "Qwen/Qwen3-Embedding-8B", "support_finetune": False, "type": "embedding"},
            {"model_name": "Qwen/Qwen3-Embedding-4B", "support_finetune": False, "type": "embedding"},
            {"model_name": "Qwen/Qwen3-Embedding-0.6B", "support_finetune": False, "type": "embedding"},
            {"model_name": "netease-youdao/bce-embedding-base_v1", "support_finetune": False, "type": "embedding"},
        ],
        "reranker_list": [
            {"model_name": "BAAI/bge-reranker-v2-m3", "support_finetune": False, "type": "rerank"},
            {"model_name": "Qwen/Qwen3-Reranker-8B", "support_finetune": False, "type": "rerank"},
            {"model_name": "Qwen/Qwen3-Reranker-4B", "support_finetune": False, "type": "rerank"},
            {"model_name": "Qwen/Qwen3-Reranker-0.6B", "support_finetune": False, "type": "rerank"},
            {"model_name": "netease-youdao/bce-reranker-base_v1", "support_finetune": False, "type": "rerank"},
        ],
        "vqa_list": [
            {"model_name": "Qwen/Qwen3-VL-32B-Instruct", "support_finetune": False, "type": "VQA"},
            {"model_name": "Qwen/Qwen3-VL-8B-Instruct", "support_finetune": False, "type": "VQA"},
            {"model_name": "Qwen/Qwen2.5-VL-72B-Instruct", "support_finetune": False, "type": "VQA"},
            {"model_name": "Qwen/Qwen2.5-VL-32B-Instruct", "support_finetune": False, "type": "VQA"},
            {"model_name": "Qwen/Qwen2-VL-72B-Instruct", "support_finetune": False, "type": "VQA"},
            {"model_name": "deepseek-ai/deepseek-vl2", "support_finetune": False, "type": "VQA"},
            {"model_name": "zai-org/GLM-4.5V", "support_finetune": False, "type": "VQA"},
        ],
        "sd_list": [
            {"model_name": "Qwen/Qwen-Image", "support_finetune": False, "type": "SD"},
            {"model_name": "Qwen/Qwen-Image-Edit", "support_finetune": False, "type": "SD"},
            {"model_name": "Kwai-Kolors/Kolors", "support_finetune": False, "type": "SD"},
        ],
        "tts_list": [
            {"model_name": "fnlp/MOSS-TTSD-v0.5", "support_finetune": False, "type": "TTS"},
            {"model_name": "FunAudioLLM/CosyVoice2-0.5B", "support_finetune": False, "type": "TTS"},
            {"model_name": "IndexTeam/IndexTTS-2", "support_finetune": False, "type": "TTS"},
        ],
        "stt_list": [
            {"model_name": "FunAudioLLM/SenseVoiceSmall", "support_finetune": False, "type": "STT"},
            {"model_name": "TeleAI/TeleSpeechASR", "support_finetune": False, "type": "STT"},
        ],
    },
}

local_model_list = {
    "llm_list": [
        "Baichuan-13B-Chat",
        "Baichuan-7B",
        "Baichuan2-13B-Chat",
        "Baichuan2-13B-Chat-4bits",
        "Baichuan2-7B-Chat",
        "Baichuan2-7B-Chat-4bits",
        "Baichuan2-7B-Intermediate-Checkpoints",
        "chatglm3-6b",
        "chatglm3-6b-128k",
        "chatglm3-6b-32k",
        "CodeLlama-13b-hf",
        "CodeLlama-34b-hf",
        "CodeLlama-70b-hf",
        "CodeLlama-7b-hf",
        "glm-4-9b-chat",
        "internlm-20b",
        "internlm-7b",
        "internlm-chat-20b",
        "internlm-chat-20b-4bit",
        "internlm-chat-7b",
        "internlm2-1_8b",
        "internlm2-20b",
        "internlm2-7b",
        "internlm2-chat-1_8b",
        "internlm2-chat-1_8b-sft",
        "internlm2-chat-20b",
        "internlm2-chat-20b-4bits",
        "internlm2-chat-20b-sft",
        "internlm2-chat-7b",
        "internlm2-chat-7b-4bits",
        "internlm2-chat-7b-sft",
        "internlm2_5-7b-chat",
        "internlm2-math-20b",
        "internlm2-math-7b",
        "Llama-2-13b",
        "Llama-2-70b",
        "Llama-2-7b",
        "Meta-Llama-3-70B",
        "Meta-Llama-3-8B",
        "Qwen-14B",
        "Qwen-1_8B",
        "Qwen-72B",
        "Qwen-7B",
        "Qwen1.5-0.5B-Chat",
        "Qwen1.5-1.8B",
        "Qwen1.5-14B",
        "Qwen1.5-14B-Chat",
        "Qwen1.5-4B",
        "Qwen1.5-72B",
        "Qwen1.5-7B",
        "Qwen2-72B-Instruct",
        "Qwen2-72B-Instruct-AWQ",
        "Qwen2-7B-Instruct",
        "InternVL-Chat-V1-5",
        "llava-1.5-13b-hf",
        "llava-1.5-7b-hf",
        "Mini-InternVL-Chat-2B-V1-5",
        "bark",
        "ChatTTS",
        "musicgen-medium",
        "musicgen-stereo-small",
        "stable-diffusion-3-medium",
        "SenseVoiceSmall",
    ],
    "embedding_list": ["bge-large-zh-v1.5", "bge-m3"],
    "reranker_list": ["bge-reranker-large"],
}

local_model_builtins = {
    "localLLM": [
        {"model_key": "Baichuan-13B-Chat", "model_from": "modelscope"},
        {"model_key": "Baichuan-7B", "model_from": "modelscope"},
        {"model_key": "Baichuan2-13B-Chat", "model_from": "modelscope"},
        {"model_key": "Baichuan2-13B-Chat-4bits", "model_from": "modelscope"},
        {"model_key": "Baichuan2-7B-Chat", "model_from": "modelscope"},
        {"model_key": "Baichuan2-7B-Chat-4bits", "model_from": "modelscope"},
        {
            "model_key": "Baichuan2-7B-Intermediate-Checkpoints",
            "model_from": "modelscope",
        },
        {"model_key": "chatglm3-6b", "model_from": "modelscope"},
        {"model_key": "chatglm3-6b-128k", "model_from": "modelscope"},
        {"model_key": "chatglm3-6b-32k", "model_from": "modelscope"},
        {"model_key": "CodeLlama-13b-hf", "model_from": "modelscope"},
        {"model_key": "CodeLlama-34b-hf", "model_from": "modelscope"},
        {"model_key": "CodeLlama-70b-hf", "model_from": "modelscope"},
        {"model_key": "CodeLlama-7b-hf", "model_from": "modelscope"},
        {"model_key": "glm-4-9b-chat", "model_from": "modelscope"},
        {"model_key": "internlm-20b", "model_from": "modelscope"},
        {"model_key": "internlm-7b", "model_from": "modelscope"},
        {"model_key": "internlm-chat-20b", "model_from": "modelscope"},
        {"model_key": "internlm-chat-20b-4bit", "model_from": "modelscope"},
        {"model_key": "internlm-chat-7b", "model_from": "modelscope"},
        {"model_key": "internlm2-1_8b", "model_from": "modelscope"},
        {"model_key": "internlm2-20b", "model_from": "modelscope"},
        {"model_key": "internlm2-7b", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-1_8b", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-1_8b-sft", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-20b", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-20b-4bits", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-20b-sft", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-7b", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-7b-4bits", "model_from": "modelscope"},
        {"model_key": "internlm2-chat-7b-sft", "model_from": "modelscope"},
        {"model_key": "internlm2_5-7b-chat", "model_from": "modelscope"},
        {"model_key": "internlm2-math-20b", "model_from": "modelscope"},
        {"model_key": "internlm2-math-7b", "model_from": "modelscope"},
        {"model_key": "Llama-2-13b", "model_from": "modelscope"},
        {"model_key": "Llama-2-70b", "model_from": "modelscope"},
        {"model_key": "Llama-2-7b", "model_from": "modelscope"},
        {"model_key": "Meta-Llama-3-70B", "model_from": "modelscope"},
        {"model_key": "Meta-Llama-3-8B", "model_from": "modelscope"},
        {"model_key": "Qwen-14B", "model_from": "modelscope"},
        {"model_key": "Qwen-1_8B", "model_from": "modelscope"},
        {"model_key": "Qwen-72B", "model_from": "modelscope"},
        {"model_key": "Qwen-7B", "model_from": "modelscope"},
        {"model_key": "Qwen1.5-0.5B-Chat", "model_from": "modelscope"},
        {"model_key": "Qwen1.5-1.8B", "model_from": "modelscope"},
        {"model_key": "Qwen1.5-14B", "model_from": "modelscope"},
        {"model_key": "Qwen1.5-14B-Chat", "model_from": "modelscope"},
        {"model_key": "Qwen1.5-4B", "model_from": "modelscope"},
        {"model_key": "Qwen1.5-72B", "model_from": "modelscope"},
        {"model_key": "Qwen1.5-7B", "model_from": "modelscope"},
        {"model_key": "Qwen2-72B-Instruct", "model_from": "modelscope"},
        {"model_key": "Qwen2-72B-Instruct-AWQ", "model_from": "modelscope"},
        {"model_key": "Qwen2-7B-Instruct", "model_from": "modelscope"},
    ],
    "VQA": [
        {"model_key": "InternVL-Chat-V1-5", "model_from": "modelscope"},
        {"model_key": "Mini-InternVL-Chat-2B-V1-5", "model_from": "modelscope"},
        {"model_key": "llava-1.5-13b-hf", "model_from": "modelscope"},
        {"model_key": "llava-1.5-7b-hf", "model_from": "modelscope"},
    ],
    "SD": [{"model_key": "stable-diffusion-3-medium", "model_from": "modelscope"}],
    "TTS": [
        {"model_key": "ChatTTS", "model_from": "modelscope"},
        {"model_key": "musicgen-stereo-small", "model_from": "modelscope"},
        {"model_key": "musicgen-medium", "model_from": "modelscope"},
        {"model_key": "bark", "model_from": "modelscope"},
    ],
    "STT": [{"model_key": "SenseVoiceSmall", "model_from": "modelscope"}],
    "reranker": [{"model_key": "bge-reranker-large", "model_from": "modelscope"}],
    "Embedding": [
        {"model_key": "bge-large-zh-v1.5", "model_from": "modelscope"},
        {"model_key": "bge-m3", "model_from": "modelscope"},
    ],
}

# AMS内置的模型
ams_model_list = [
    {
        "name": "internlm2_5-7b-chat",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": True,
        "model_kind": "localLLM",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "sensevoicesmall",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "STT",
        "framework": "SenseVoiceDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "Qwen2.5-72B-Instruct-AWQ",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "localLLM",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "Qwen2.5-72B-Instruct",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": True,
        "model_kind": "localLLM",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "QwQ-32B",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": True,
        "model_kind": "localLLM",
        "framework": "Mindie",
        "endpoint": "/generate",
    },
    {
        "name": "qwen2.5-vl-3b-instruct",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "VQA",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "Mini-InternVL-Chat-2B-V1-5",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "VQA",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "Qwen2.5-VL-32B-Instruct",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "VQA",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "Qwen3-32B",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": True,
        "model_kind": "localLLM",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "bge-reranker-v2-m3",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "reranker",
        "framework": "RerankerDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "bge-m3",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "Embedding",
        "framework": "EmbeddingDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "BGE-VL-v1.5-mmeb",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "Embedding",
        "framework": "EmbeddingDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "ChatTTS-new",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "TTS",
        "framework": "ChatTTSDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "llama-3-8b-Instruct",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": True,
        "model_kind": "localLLM",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "Meta-Llama-3-8B-Instruct",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": True,
        "model_kind": "localLLM",
        "framework": "LMDeploy",
        "endpoint": "/v1/chat/interactive",
    },
    {
        "name": "PP-OCRv5_server",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "OCR",
        "framework": "OCRDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "PP-OCRv5_mobile",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "OCR",
        "framework": "OCRDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "PP-OCRv4_server",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "OCR",
        "framework": "OCRDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "PP-OCRv4_mobile",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "OCR",
        "framework": "OCRDeploy",
        "endpoint": "/generate",
    },
    {
        "name": "bark",
        "model_type": "local",
        "model_status": 3,
        "is_finetune_model": False,
        "can_finetune_model": False,
        "model_kind": "TTS",
        "framework": "BarkDeploy",
        "endpoint": "/generate",
    },
]

for item in ams_model_list:
    item["model_name"] = item["name"]
